
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Apr 30 18:47:39 CEST 2020
//----------------------------------------------------

package herbadji.svg.api;

import herbadji.svg.api.elements.*;
import herbadji.svg.api.expressions.*;

/** CUP v0.11a beta 20060608 generated parser.
  * @version Thu Apr 30 18:47:39 CEST 2020
  */
public class Parser extends java_cup.runtime.lr_parser {

  /** Default constructor. */
  public Parser() {super();}

  /** Constructor which sets the default scanner. */
  public Parser(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public Parser(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\024\000\002\002\003\000\002\002\004\000\002\003" +
    "\002\000\002\003\004\000\002\004\004\000\002\006\005" +
    "\000\002\006\005\000\002\006\005\000\002\006\005\000" +
    "\002\006\005\000\002\006\004\000\002\006\004\000\002" +
    "\006\003\000\002\006\003\000\002\005\002\000\002\005" +
    "\010\000\002\005\007\000\002\005\005\000\002\005\003" +
    "\000\002\005\011" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\062\000\020\002\uffff\004\uffff\005\uffff\006\uffff\007" +
    "\uffff\010\uffff\015\uffff\001\002\000\004\002\064\001\002" +
    "\000\020\002\001\004\010\005\012\006\007\007\013\010" +
    "\014\015\ufff3\001\002\000\020\002\ufffe\004\ufffe\005\ufffe" +
    "\006\ufffe\007\ufffe\010\ufffe\015\ufffe\001\002\000\004\004" +
    "\057\001\002\000\004\017\055\001\002\000\004\015\054" +
    "\001\002\000\004\015\uffef\001\002\000\004\004\050\001" +
    "\002\000\004\004\015\001\002\000\014\004\016\011\020" +
    "\012\017\020\021\024\023\001\002\000\024\004\ufff4\011" +
    "\ufff4\012\ufff4\013\ufff4\014\ufff4\015\ufff4\020\ufff4\021\ufff4" +
    "\024\ufff4\001\002\000\014\004\016\011\020\012\017\020" +
    "\021\024\023\001\002\000\014\004\016\011\020\012\017" +
    "\020\021\024\023\001\002\000\014\004\016\011\020\012" +
    "\017\020\021\024\023\001\002\000\020\004\016\011\026" +
    "\012\025\013\024\014\027\020\021\024\023\001\002\000" +
    "\024\004\ufff5\011\ufff5\012\ufff5\013\ufff5\014\ufff5\015\ufff5" +
    "\020\ufff5\021\ufff5\024\ufff5\001\002\000\014\004\016\011" +
    "\020\012\017\020\021\024\023\001\002\000\014\004\016" +
    "\011\020\012\017\020\021\024\023\001\002\000\014\004" +
    "\016\011\020\012\017\020\021\024\023\001\002\000\014" +
    "\004\016\011\020\012\017\020\021\024\023\001\002\000" +
    "\020\004\016\011\026\012\025\013\024\014\027\020\021" +
    "\024\023\001\002\000\020\004\016\011\026\012\025\013" +
    "\024\014\027\020\021\024\023\001\002\000\020\004\016" +
    "\011\026\012\025\013\024\014\027\020\021\024\023\001" +
    "\002\000\014\011\035\012\034\013\024\014\027\015\uffee" +
    "\001\002\000\014\004\016\011\020\012\017\020\021\024" +
    "\023\001\002\000\014\004\016\011\020\012\017\020\021" +
    "\024\023\001\002\000\024\004\ufffb\011\ufffb\012\ufffb\013" +
    "\024\014\027\015\ufffb\020\ufffb\021\ufffb\024\ufffb\001\002" +
    "\000\024\004\ufffa\011\ufffa\012\ufffa\013\024\014\027\015" +
    "\ufffa\020\ufffa\021\ufffa\024\ufffa\001\002\000\024\004\ufff8" +
    "\011\ufff8\012\ufff8\013\ufff8\014\ufff8\015\ufff8\020\ufff8\021" +
    "\ufff8\024\ufff8\001\002\000\022\004\ufffb\011\ufffb\012\ufffb" +
    "\013\024\014\027\015\ufff7\020\ufffb\024\ufffb\001\002\000" +
    "\022\004\ufffa\011\ufffa\012\ufffa\013\024\014\027\015\ufff6" +
    "\020\ufffa\024\ufffa\001\002\000\024\004\ufff9\011\ufff9\012" +
    "\ufff9\013\ufff9\014\ufff9\015\ufff9\020\ufff9\021\ufff9\024\ufff9" +
    "\001\002\000\014\011\035\012\034\013\024\014\027\021" +
    "\045\001\002\000\024\004\ufffc\011\ufffc\012\ufffc\013\ufffc" +
    "\014\ufffc\015\ufffc\020\ufffc\021\ufffc\024\ufffc\001\002\000" +
    "\024\004\ufff7\011\ufff7\012\ufff7\013\ufff7\014\ufff7\015\ufff7" +
    "\020\ufff7\021\ufff7\024\ufff7\001\002\000\024\004\ufff6\011" +
    "\ufff6\012\ufff6\013\ufff6\014\ufff6\015\ufff6\020\ufff6\021\ufff6" +
    "\024\ufff6\001\002\000\014\004\016\011\020\012\017\020" +
    "\021\024\023\001\002\000\020\004\016\011\026\012\025" +
    "\013\024\014\027\020\021\024\023\001\002\000\020\004" +
    "\016\011\026\012\025\013\024\014\027\020\021\024\023" +
    "\001\002\000\014\011\035\012\034\013\024\014\027\015" +
    "\ufff1\001\002\000\020\002\ufffd\004\ufffd\005\ufffd\006\ufffd" +
    "\007\ufffd\010\ufffd\015\ufffd\001\002\000\014\004\016\011" +
    "\020\012\017\020\021\024\023\001\002\000\014\011\035" +
    "\012\034\013\024\014\027\015\ufff0\001\002\000\014\004" +
    "\016\011\020\012\017\020\021\024\023\001\002\000\020" +
    "\004\016\011\026\012\025\013\024\014\027\020\021\024" +
    "\023\001\002\000\020\004\016\011\026\012\025\013\024" +
    "\014\027\020\021\024\023\001\002\000\020\004\016\011" +
    "\026\012\025\013\024\014\027\020\021\024\023\001\002" +
    "\000\014\011\035\012\034\013\024\014\027\015\ufff2\001" +
    "\002\000\004\002\000\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\062\000\006\002\003\003\004\001\001\000\002\001" +
    "\001\000\006\004\005\005\010\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\004" +
    "\006\021\001\001\000\002\001\001\000\004\006\046\001" +
    "\001\000\004\006\045\001\001\000\004\006\043\001\001" +
    "\000\004\006\027\001\001\000\002\001\001\000\004\006" +
    "\042\001\001\000\004\006\041\001\001\000\004\006\040" +
    "\001\001\000\004\006\037\001\001\000\004\006\030\001" +
    "\001\000\004\006\031\001\001\000\004\006\032\001\001" +
    "\000\002\001\001\000\004\006\036\001\001\000\004\006" +
    "\035\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\004\006\050\001\001\000\004\006" +
    "\051\001\001\000\004\006\052\001\001\000\002\001\001" +
    "\000\002\001\001\000\004\006\055\001\001\000\002\001" +
    "\001\000\004\006\057\001\001\000\004\006\060\001\001" +
    "\000\004\006\061\001\001\000\004\006\062\001\001\000" +
    "\002\001\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP_actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP_actions();
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP_do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 1;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}



    public void report_error(String message, Object info) {
        StringBuffer m = new StringBuffer("Error");
		m.append (info.toString());
        m.append(" : "+message);
        System.err.println(m.toString());
    }
   
    public void report_fatal_error(String message, Object info) {
        report_error(message, info);
        System.exit(1);
    }
    
	private SVGContext context;
	
    public void setContext (SVGContext context) {
    	this.context = context;
    }

    public SVGContext getContext () {
		return context;
    }
    
    public SVGFactory getFactory () {
		return getContext().getFactory();
	}



/** Cup generated class to encapsulate user supplied action code.*/
class CUP_actions {

  /** Constructor */

  /** Method with the actual generated action code. */
  public final java_cup.runtime.Symbol CUP_do_action(
    int                        CUP_act_num,
    java_cup.runtime.lr_parser CUP_parser,
    java.util.Stack            CUP_stack,
    int                        CUP_top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP_result;

      /* select the action based on the action number */
      switch (CUP_act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // Instruction ::= ANIMATE ID expr expr expr expr expr 
            {
              Node RESULT =null;
		String id = (String)((java_cup.runtime.Symbol) CUP_stack.elementAt(CUP_top-5)).value;
		ExpressionNode fromX = (ExpressionNode)((java_cup.runtime.Symbol) CUP_stack.elementAt(CUP_top-4)).value;
		ExpressionNode fromY = (ExpressionNode)((java_cup.runtime.Symbol) CUP_stack.elementAt(CUP_top-3)).value;
		ExpressionNode toX = (ExpressionNode)((java_cup.runtime.Symbol) CUP_stack.elementAt(CUP_top-2)).value;
		ExpressionNode toY = (ExpressionNode)((java_cup.runtime.Symbol) CUP_stack.elementAt(CUP_top-1)).value;
		ExpressionNode time = (ExpressionNode)((java_cup.runtime.Symbol) CUP_stack.peek()).value;
		 RESULT = getFactory().animateNodes(id, fromX, fromY, toX, toY, time); 
              CUP_result = getSymbolFactory().newSymbol("Instruction",3, RESULT);
            }
          return CUP_result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // Instruction ::= TEXT 
            {
              Node RESULT =null;
		String text = (String)((java_cup.runtime.Symbol) CUP_stack.peek()).value;
		 RESULT = getFactory().createNodeConstantString (text); 
              CUP_result = getSymbolFactory().newSymbol("Instruction",3, RESULT);
            }
          return CUP_result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // Instruction ::= ID SET expr 
            {
              Node RESULT =null;
		String id = (String)((java_cup.runtime.Symbol) CUP_stack.elementAt(CUP_top-2)).value;
		ExpressionNode v = (ExpressionNode)((java_cup.runtime.Symbol) CUP_stack.peek()).value;
		 /*RESULT = */getFactory().createNodeSetVariable (id, v); 
              CUP_result = getSymbolFactory().newSymbol("Instruction",3, RESULT);
            }
          return CUP_result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // Instruction ::= CIRCLE ID expr expr expr 
            {
              Node RESULT =null;
		String id = (String)((java_cup.runtime.Symbol) CUP_stack.elementAt(CUP_top-3)).value;
		ExpressionNode x = (ExpressionNode)((java_cup.runtime.Symbol) CUP_stack.elementAt(CUP_top-2)).value;
		ExpressionNode y = (ExpressionNode)((java_cup.runtime.Symbol) CUP_stack.elementAt(CUP_top-1)).value;
		ExpressionNode r = (ExpressionNode)((java_cup.runtime.Symbol) CUP_stack.peek()).value;
		 RESULT = getFactory().createCircle(id, x, y, r); 
              CUP_result = getSymbolFactory().newSymbol("Instruction",3, RESULT);
            }
          return CUP_result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // Instruction ::= RECTANGLE ID expr expr expr expr 
            {
              Node RESULT =null;
		String id = (String)((java_cup.runtime.Symbol) CUP_stack.elementAt(CUP_top-4)).value;
		ExpressionNode x = (ExpressionNode)((java_cup.runtime.Symbol) CUP_stack.elementAt(CUP_top-3)).value;
		ExpressionNode y = (ExpressionNode)((java_cup.runtime.Symbol) CUP_stack.elementAt(CUP_top-2)).value;
		ExpressionNode w = (ExpressionNode)((java_cup.runtime.Symbol) CUP_stack.elementAt(CUP_top-1)).value;
		ExpressionNode h = (ExpressionNode)((java_cup.runtime.Symbol) CUP_stack.peek()).value;
		 RESULT = getFactory().createRectangle(id, x, y, w, h); 
              CUP_result = getSymbolFactory().newSymbol("Instruction",3, RESULT);
            }
          return CUP_result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // Instruction ::= 
            {
              Node RESULT =null;
		 RESULT = null; 
              CUP_result = getSymbolFactory().newSymbol("Instruction",3, RESULT);
            }
          return CUP_result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // expr ::= ID 
            {
              ExpressionNode RESULT =null;
		String id = (String)((java_cup.runtime.Symbol) CUP_stack.peek()).value;
		 RESULT = getFactory().createNodeGetVariable (id); 
              CUP_result = getSymbolFactory().newSymbol("expr",4, RESULT);
            }
          return CUP_result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // expr ::= INT 
            {
              ExpressionNode RESULT =null;
		Integer n = (Integer)((java_cup.runtime.Symbol) CUP_stack.peek()).value;
		 RESULT = getFactory().createNodeConstantInteger (n); 
              CUP_result = getSymbolFactory().newSymbol("expr",4, RESULT);
            }
          return CUP_result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // expr ::= SUB expr 
            {
              ExpressionNode RESULT =null;
		ExpressionNode e = (ExpressionNode)((java_cup.runtime.Symbol) CUP_stack.peek()).value;
		 RESULT = getFactory().createNodeMinus (e); 
              CUP_result = getSymbolFactory().newSymbol("expr",4, RESULT);
            }
          return CUP_result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // expr ::= ADD expr 
            {
              ExpressionNode RESULT =null;
		ExpressionNode e = (ExpressionNode)((java_cup.runtime.Symbol) CUP_stack.peek()).value;
		 RESULT = getFactory().createNodePlus (e); 
              CUP_result = getSymbolFactory().newSymbol("expr",4, RESULT);
            }
          return CUP_result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // expr ::= expr DIV expr 
            {
              ExpressionNode RESULT =null;
		ExpressionNode e1 = (ExpressionNode)((java_cup.runtime.Symbol) CUP_stack.elementAt(CUP_top-2)).value;
		ExpressionNode e2 = (ExpressionNode)((java_cup.runtime.Symbol) CUP_stack.peek()).value;
		 RESULT = getFactory().createNodeDiv (e1, e2); 
              CUP_result = getSymbolFactory().newSymbol("expr",4, RESULT);
            }
          return CUP_result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // expr ::= expr MULT expr 
            {
              ExpressionNode RESULT =null;
		ExpressionNode e1 = (ExpressionNode)((java_cup.runtime.Symbol) CUP_stack.elementAt(CUP_top-2)).value;
		ExpressionNode e2 = (ExpressionNode)((java_cup.runtime.Symbol) CUP_stack.peek()).value;
		 RESULT = getFactory().createNodeMult (e1, e2); 
              CUP_result = getSymbolFactory().newSymbol("expr",4, RESULT);
            }
          return CUP_result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // expr ::= expr SUB expr 
            {
              ExpressionNode RESULT =null;
		ExpressionNode e1 = (ExpressionNode)((java_cup.runtime.Symbol) CUP_stack.elementAt(CUP_top-2)).value;
		ExpressionNode e2 = (ExpressionNode)((java_cup.runtime.Symbol) CUP_stack.peek()).value;
		 RESULT = getFactory().createNodeSub (e1, e2); 
              CUP_result = getSymbolFactory().newSymbol("expr",4, RESULT);
            }
          return CUP_result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // expr ::= expr ADD expr 
            {
              ExpressionNode RESULT =null;
		ExpressionNode e1 = (ExpressionNode)((java_cup.runtime.Symbol) CUP_stack.elementAt(CUP_top-2)).value;
		ExpressionNode e2 = (ExpressionNode)((java_cup.runtime.Symbol) CUP_stack.peek()).value;
		 RESULT = getFactory().createNodeAdd (e1, e2); 
              CUP_result = getSymbolFactory().newSymbol("expr",4, RESULT);
            }
          return CUP_result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // expr ::= OPEN_PARENTHESIS expr CLOSE_PARENTHESIS 
            {
              ExpressionNode RESULT =null;
		ExpressionNode e = (ExpressionNode)((java_cup.runtime.Symbol) CUP_stack.elementAt(CUP_top-1)).value;
		 RESULT = e; 
              CUP_result = getSymbolFactory().newSymbol("expr",4, RESULT);
            }
          return CUP_result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // Definition ::= Instruction TERM 
            {
              Object RESULT =null;
		Node inst = (Node)((java_cup.runtime.Symbol) CUP_stack.elementAt(CUP_top-1)).value;
		 ; 
              CUP_result = getSymbolFactory().newSymbol("Definition",2, RESULT);
            }
          return CUP_result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // Definitions ::= Definitions Definition 
            {
              Object RESULT =null;

              CUP_result = getSymbolFactory().newSymbol("Definitions",1, RESULT);
            }
          return CUP_result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // Definitions ::= 
            {
              Object RESULT =null;

              CUP_result = getSymbolFactory().newSymbol("Definitions",1, RESULT);
            }
          return CUP_result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // $START ::= Commandes EOF 
            {
              Object RESULT =null;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP_stack.elementAt(CUP_top-1)).value;
		RESULT = start_val;
              CUP_result = getSymbolFactory().newSymbol("$START",0, RESULT);
            }
          /* ACCEPT */
          CUP_parser.done_parsing();
          return CUP_result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // Commandes ::= Definitions 
            {
              Object RESULT =null;

              CUP_result = getSymbolFactory().newSymbol("Commandes",0, RESULT);
            }
          return CUP_result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number found in internal parse table");

        }
    }
}

}
