
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Apr 30 18:47:39 CEST 2020
//----------------------------------------------------

package herbadji.svg.api;

/** CUP generated interface containing symbol constants. */
public interface Sym {
  /* terminals */
  public static final int UNARY_PLUS = 16;
  public static final int OPEN_PARENTHESIS = 14;
  public static final int INT = 18;
  public static final int UNARY_MINUS = 17;
  public static final int CIRCLE = 5;
  public static final int ID = 2;
  public static final int SUB = 8;
  public static final int MULT = 9;
  public static final int EOF = 0;
  public static final int SET = 13;
  public static final int DIV = 10;
  public static final int ADD = 7;
  public static final int RECTANGLE = 4;
  public static final int SEP = 12;
  public static final int error = 1;
  public static final int ANIMATE = 6;
  public static final int TEXT = 3;
  public static final int CLOSE_PARENTHESIS = 15;
  public static final int TERM = 11;
}

